name: "Build"
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: sunziping2016
          # Create a personal auth token from https://app.cachix.org/personal-auth-tokens,
          # login to cachix, and then generate a signing key and provision it.
          #     cachix authtoken --stdin  # paste personal auth token
          #     cachix generate-keypair sunziping2016
          #     gh secret set CACHIX_SIGNING_KEY  # paste signing key
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: Run nix flake show
        run: nix flake show --all-systems
      - name: Run nix flake check
        run: nix flake check --all-systems
