name: "Terragrunt GitHub Actions"

on:
  push:
    branches:
      - "master"
    paths:
      - secrets/terraform/**
      - terraform/**
  pull_request:
    branches:
      - "master"
    paths:
      - secrets/terraform/**
      - terraform/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TERRAGRUNT_NON_INTERACTIVE: "true"
  TF_IN_AUTOMATION: "true"

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            accept-flake-config = true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
      - uses: aliyun/configure-aliyun-credentials-action@v1
        with:
          role-to-assume: ${{ vars.ALIYUN_ROLE_TO_ASSUME }}
          oidc-provider-arn: ${{ vars.ALIYUN_OIDC_PROVIDER_ARN  }}
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: nicknovitski/nix-develop@v1
      - name: Validate terragrunt configuration
        run: terragrunt run-all validate
        working-directory: terraform
      - name: Plan
        run: terragrunt run-all plan
        working-directory: terraform
        env:
          TERRAGRUNT_EXCLUDE_DIR: bootstrap,github-action
