name: "Terragrunt GitHub Actions"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TERRAGRUNT_NON_INTERACTIVE: "true"

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            accept-flake-config = true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::137927498482:role/github-oidc-provider-aws
      - uses: aliyun/configure-aliyun-credentials-action@v1
        with:
          role-to-assume: acs:ram::1426844216480741:role/github-oidc-provider-aliyun
          oidc-provider-arn: acs:ram::1426844216480741:oidc-provider/GitHub
      - run: nix develop --command terragrunt run-all state list
